FROM node:buster

# Set working directory
WORKDIR /app

# Add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH
ENV CHOKIDAR_USEPOLLING true

# Install and cache app dependencies
COPY package.json .
RUN npm install --silent
RUN npm install react-scripts@3.0.1 -g --silent

EXPOSE 3000

# Start app
CMD ["npm", "start"]